# Generated by Django 5.1.15 on 2026-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform admin'), ('PHARMACY_OWNER', 'Pharmacy owner'), ('PHARMACY_STAFF', 'Pharmacy staff'), ('DOCTOR', 'Doctor'), ('CUSTOMER', 'Customer'), ('DRIVER', 'Delivery driver')], max_length=32),
        ),
    ]
