# Generated by Django 5.1.15 on 2026-08-20 11:17

from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """Everyone who already has an account predates this requirement - don't lock anyone
    out of checkout retroactively. Only new signups from here on start unverified."""
    User = apps.get_model("accounts", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Shoppers must verify before checkout; other roles are created by staff and pre-verified.'),
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
    ]
