# Generated by Django 5.1.15 on 2026-08-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number for deliveries. Not used for sign-in or verification.', max_length=40),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True)),
                ('delivery_updates', models.BooleanField(default=True)),
                ('prescription_reminders', models.BooleanField(default=True)),
                ('refill_reminders', models.BooleanField(default=True)),
                ('product_news', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
