# Generated by Django 5.1.15 on 2026-08-29 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_notificationpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy_metres', models.PositiveIntegerField(blank=True, help_text='What the device reported. A very loose fix is still usable for ranking pharmacies a few km apart.', null=True)),
                ('source', models.CharField(choices=[('DEVICE', 'Device location'), ('ADDRESS', 'Picked from a saved address'), ('MANUAL', 'Entered by hand')], default='DEVICE', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Area name resolved at capture time, for showing the person what we think 'near me' means.", max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
