# Generated by Django 5.1.15 on 2026-08-20 00:09

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default=apps.payments.models.default_currency, max_length=3),
        ),
    ]
