# Generated by Django 5.1.15 on 2026-08-27 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash on delivery')], max_length=10)),
                ('brand', models.CharField(blank=True, help_text='Card only, e.g. Visa.', max_length=40)),
                ('last4', models.CharField(blank=True, help_text='Card only. The last four digits, never the full number.', max_length=4)),
                ('expiry', models.CharField(blank=True, help_text='Card only, MM/YY.', max_length=7)),
                ('provider_token', models.CharField(blank=True, help_text='Opaque gateway reference, if one exists.', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_payment_method_per_user')],
            },
        ),
    ]
