# Generated by Django 5.1.15 on 2026-07-04 10:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('area', models.CharField(db_index=True, max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'area'], name='pharmacies__city_a81d0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'area'), name='unique_pharmacy_name_per_area')],
            },
        ),
    ]
