# Generated by Django 5.1.15 on 2026-07-30 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='accepts_online_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='closes_at',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='delivery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='fulfillment_success_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percent of accepted orders handed over without a shortfall.', max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opens_at',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='order_preparation_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='orders_fulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='orders_rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='public_max_quantity_per_item',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides the platform default cap on publicly visible/orderable units.', null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
