# Generated by Django 5.1.15 on 2026-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacyapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_on_call',
            field=models.BooleanField(db_index=True, default=False, help_text="Currently on Lebanon's pharmacy duty roster ('de garde') - reachable outside normal hours."),
        ),
    ]
