# Generated by Django 5.1.15 on 2026-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_pharmacy_is_on_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pos_system',
            field=models.CharField(blank=True, choices=[('NONE', 'No POS system (dashboard/manual only)'), ('SOFTPHARM', 'SoftPharm (NIT)'), ('OTHER', 'Other')], db_index=True, default='NONE', help_text='Which POS/pharmacy-management software this pharmacy runs, if any - drives which connector template applies.', max_length=20),
        ),
    ]
