# Generated by Django 5.1.15 on 2026-07-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['pharmacy', 'medicine', 'expiry_date'], name='inventory_i_pharmac_3a609c_idx'),
        ),
    ]
