# Generated by Django 5.1.15 on 2026-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
