# Generated by Django 5.1.15 on 2026-08-21 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_webhookdelivery_status'),
        ('inventory', '0003_inventorybatch_reserved_quantity'),
        ('medicines', '0004_medicine_drug_schedule'),
        ('pharmacies', '0003_pharmacyapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='last_pos_observed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When a connected pharmacy's POS last confirmed this exact quantity, via sync.", null=True),
        ),
        migrations.CreateModel(
            name='ReservationShortfall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_on_hand', models.PositiveIntegerField(help_text='What the POS reported on this sync.')),
                ('reserved_quantity', models.PositiveIntegerField(help_text='What the platform had promised to shoppers at detection time.')),
                ('shortfall_units', models.PositiveIntegerField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfalls', to='inventory.inventorybatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_shortfalls', to='medicines.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_shortfalls', to='pharmacies.pharmacy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reservation_shortfalls', to=settings.AUTH_USER_MODEL)),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_shortfalls', to='integrations.syncrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pharmacy', 'resolved_at'], name='inventory_r_pharmac_cc8507_idx')],
            },
        ),
    ]
