# Generated by Django 5.1.15 on 2026-08-28 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.CharField(db_index=True, help_text="Which role's assistant this thread is talking to - see apps.assistant.personas.", max_length=32)),
                ('title', models.CharField(blank=True, help_text='First thing the person asked, trimmed. Only for listing threads back to them.', max_length=120)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for a visitor who was not signed in when the thread started.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'From the person'), ('ASSISTANT', 'From the assistant')], max_length=10)),
                ('body', models.TextField()),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='[{name, arguments}] the assistant called to produce this reply. Kept so an answer can be traced back to the data it actually read.')),
                ('provider', models.CharField(blank=True, help_text='Which assistant provider produced this reply (blank on user messages).', max_length=32)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
