# Generated by Django 5.1.15 on 2026-07-04 10:34

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('form', models.CharField(blank=True, max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('classification', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('brand_name'), django.db.models.functions.text.Lower('strength'), django.db.models.functions.text.Lower('form'), condition=models.Q(('is_active', True)), name='unique_active_medicine_variant')],
            },
        ),
        migrations.CreateModel(
            name='MedicineAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('alias_type', models.CharField(choices=[('BRAND_VARIATION', 'Brand variation'), ('GENERIC', 'Generic'), ('MISSPELLING', 'Misspelling'), ('IMPORT_NAME', 'Import name'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='medicines.medicine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('alias'), models.F('medicine'), name='unique_alias_per_medicine')],
            },
        ),
    ]
