# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('MEDICINE', 'Medicine (MoPH regulated price)'), ('SUPPLEMENT', 'Supplement'), ('PARAPHARMACY', 'Parapharmacy / other')], db_index=True, default='MEDICINE', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price_regime',
            field=models.CharField(choices=[('REGULATED', 'MoPH regulated'), ('FREE', 'Free pricing')], db_index=True, default='REGULATED', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='regulated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Public price set by the Ministry of Public Health. Required when price_regime is REGULATED.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='regulated_price_reference',
            field=models.CharField(blank=True, help_text='MoPH price list / decision reference.', max_length=120),
        ),
        migrations.AddField(
            model_name='medicine',
            name='regulated_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
