# Generated by Django 5.1.15 on 2026-08-19 23:28

import apps.medicines.models
import apps.medicines.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_category_medicine_price_regime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, help_text='Product photo shown to shoppers.', null=True, storage=apps.medicines.storage.ProductImageStorage(), upload_to=apps.medicines.models.medicine_image_path),
        ),
    ]
