# Generated by Django 5.1.15 on 2026-08-19 23:55

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def deactivate_duplicate_active_variants(apps, schema_editor):
    """Make legacy medicine data satisfy the current active-variant constraint.

    An older local schema included ``presentation`` in the unique key. When
    SQLite rebuilds the table to add ``drug_schedule``, Django restores the
    current three-column constraint and those presentation variants collide.
    Keep the oldest variant active and preserve the remaining rows as inactive.
    """

    Medicine = apps.get_model("medicines", "Medicine")
    database = schema_editor.connection.alias
    medicines = Medicine.objects.using(database)

    duplicate_keys = list(
        medicines.filter(is_active=True)
        .annotate(
            normalized_brand=Lower("brand_name"),
            normalized_strength=Lower("strength"),
            normalized_form=Lower("form"),
        )
        .values("normalized_brand", "normalized_strength", "normalized_form")
        .annotate(total=Count("pk"))
        .filter(total__gt=1)
    )

    for key in duplicate_keys:
        duplicate_ids = list(
            medicines.filter(is_active=True)
            .annotate(
                normalized_brand=Lower("brand_name"),
                normalized_strength=Lower("strength"),
                normalized_form=Lower("form"),
            )
            .filter(
                normalized_brand=key["normalized_brand"],
                normalized_strength=key["normalized_strength"],
                normalized_form=key["normalized_form"],
            )
            .order_by("created_at", "pk")
            .values_list("pk", flat=True)
        )
        medicines.filter(pk__in=duplicate_ids[1:]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_image'),
    ]

    operations = [
        migrations.RunPython(
            deactivate_duplicate_active_variants,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_schedule',
            field=models.CharField(choices=[('NONE', 'Not scheduled'), ('PRESCRIPTION', 'Prescription required'), ('CONTROLLED', 'Controlled substance')], db_index=True, default='NONE', max_length=20),
        ),
    ]
