# Generated by Django 5.1.15 on 2026-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_schedule',
            field=models.CharField(choices=[('NONE', 'Not scheduled'), ('PRESCRIPTION', 'Prescription required'), ('CONTROLLED', 'Controlled substance')], db_index=True, default='NONE', max_length=20),
        ),
    ]
