# Generated by Django 5.1.15 on 2026-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_drug_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinealias',
            name='alias_type',
            field=models.CharField(choices=[('BRAND_VARIATION', 'Brand variation'), ('GENERIC', 'Generic'), ('MISSPELLING', 'Misspelling'), ('IMPORT_NAME', 'Import name'), ('TRANSLITERATION', 'Transliteration (e.g. Arabic script)'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
    ]
