# Generated by Django 5.1.15 on 2026-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_active_regulated_medicine_has_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='market_status',
            field=models.CharField(choices=[('MARKETED', 'Marketed'), ('NON_MARKETED', 'Registered, not currently marketed')], db_index=True, default='MARKETED', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='moph_code',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='moph_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medicine',
            name='moph_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='moph_source',
            field=models.CharField(blank=True, choices=[('MOPH_ONLINE', 'MoPH Lebanon National Drugs Database (online)'), ('MOPH_MARKETED_EXCEL', 'MoPH WebMarketed price list (Excel)'), ('MOPH_NON_MARKETED_EXCEL', 'MoPH WebNonMarketed price list (Excel)')], max_length=32),
        ),
        migrations.AddField(
            model_name='medicine',
            name='moph_source_reference',
            field=models.CharField(blank=True, help_text='MoPH source URL/file this record was last synced from.', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='medicine',
            name='route',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
