# Generated by Django 5.1.15 on 2026-08-30 18:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='nssf_covered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='nssf_reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NSSF reference (reimbursement-ceiling) price in the same currency as regulated_price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='nssf_reimbursement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share of the reference price the NSSF reimburses, as a percentage (e.g. 80.00).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='nssf_source_reference',
            field=models.CharField(blank=True, help_text='Which NSSF list/decision (name + date) this coverage was taken from.', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='nssf_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
