# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eprescriptions', '0001_initial'),
        ('inventory', '0003_inventorybatch_reserved_quantity'),
        ('medicines', '0002_medicine_category_medicine_price_regime_and_more'),
        ('pharmacies', '0002_pharmacy_accepts_online_orders_pharmacy_closes_at_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Home', max_length=80)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('area', models.CharField(db_index=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('building_notes', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=24, unique=True)),
                ('fulfillment_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Store pickup')], default='DELIVERY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting pharmacy acceptance'), ('SCHEDULED', 'Scheduled for later'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready for pickup by driver'), ('ASSIGNED', 'Assigned to a driver'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected in store'), ('PARTIALLY_CANCELLED', 'Partially cancelled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=24)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('RECURRING', 'Recurring schedule')], default='WEB', max_length=20)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=40)),
                ('address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, db_index=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_notes', models.CharField(blank=True, max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When the shopper wants it. Null means as soon as possible.', null=True)),
                ('window_minutes', models.PositiveIntegerField(default=120, help_text='Width of the acceptable delivery window around scheduled_for.')),
                ('released_at', models.DateTimeField(blank=True, help_text='When a scheduled order entered the dispatch pool.', null=True)),
                ('items_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='eprescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('READY', 'Ready'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected in store'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handover_code', models.CharField(help_text='Shown to the driver at pickup so stock only leaves against a real task.', max_length=8)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.order')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fulfillments', to='pharmacies.pharmacy')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_fulfillments', to='sales.sale')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_price_regulated', models.BooleanField(default=False)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.orderfulfillment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='medicines.medicine')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='eprescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('was_complete', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Monthly refill', max_length=120)),
                ('items', models.JSONField(default=list, help_text='[{medicine: uuid, quantity: int}] - re-sourced each cycle, so a closed pharmacy never blocks a refill.')),
                ('interval_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('preferred_hour', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(23)])),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_orders', to='orders.deliveryaddress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='recurring_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='orders.recurringorder'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventorybatch')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.orderline')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmetDemandSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, db_index=True, max_length=120)),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('SEARCH', 'Public search'), ('BASKET', 'Basket sourcing')], default='SEARCH', max_length=20)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmet_demand', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderfulfillment',
            constraint=models.UniqueConstraint(fields=('order', 'pharmacy'), name='unique_pharmacy_per_order'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyreview',
            constraint=models.UniqueConstraint(fields=('order', 'pharmacy'), name='unique_review_per_order_pharmacy'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'scheduled_for'], name='orders_orde_status_dbdecf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='orders_orde_custome_242823_idx'),
        ),
        migrations.AddIndex(
            model_name='unmetdemandsignal',
            index=models.Index(fields=['medicine', 'created_at'], name='orders_unme_medicin_213fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='unmetdemandsignal',
            index=models.Index(fields=['area', 'created_at'], name='orders_unme_area_072ef5_idx'),
        ),
    ]
