# Generated by Django 5.1.15 on 2026-08-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0002_alter_prescription_pin_hash'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Required if any repeated item requires a prescription. Each cycle draws down its remaining quantity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_orders', to='eprescriptions.prescription'),
        ),
    ]
