# Generated by Django 5.1.15 on 2026-08-20 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0002_alter_prescription_pin_hash'),
        ('orders', '0002_recurringorder_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-supplied Idempotency-Key header. A repeat request with the same key returns the original order instead of placing a duplicate.', max_length=120),
        ),
        migrations.AddField(
            model_name='pharmacyreview',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacyreview',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Hidden reviews are excluded from the pharmacy's rating rollup."),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting pharmacy acceptance'), ('SCHEDULED', 'Scheduled for later'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready for pickup by driver'), ('ASSIGNED', 'Assigned to a driver'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected in store'), ('PARTIALLY_CANCELLED', 'Partially cancelled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Stock hold expired before a pharmacy accepted')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('READY', 'Ready'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected in store'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Stock hold expired before a pharmacy accepted')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('customer', 'idempotency_key'), name='unique_idempotency_key_per_customer'),
        ),
    ]
