# Generated by Django 5.1.15 on 2026-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_idempotency_key_pharmacyreview_hidden_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfulfillment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('READY', 'Ready'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected in store'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Stock hold expired before a pharmacy accepted'), ('DELIVERY_FAILED', 'Delivery failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
