# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pharmacies', '0002_pharmacy_accepts_online_orders_pharmacy_closes_at_and_more'),
        ('prescriptions', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('COUNTER', 'Counter'), ('PLATFORM_ORDER', 'Platform order'), ('INTEGRATION', 'Pharmacy software sync')], db_index=True, default='COUNTER', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ON_ACCOUNT', 'On client account'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pharmacy', 'client'], name='sales_sale_pharmac_0467f2_idx'),
        ),
    ]
