# Generated by Django 5.1.15 on 2026-08-27 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pharmacies', '0005_pharmacy_pos_system'),
        ('prescriptions', '0005_ocr_text'),
        ('sales', '0002_sale_channel_sale_client_alter_sale_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'invoice_number'), name='unique_invoice_number_per_pharmacy'),
        ),
    ]
