# Generated by Django 5.1.15 on 2026-08-22 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orderfulfillment_status'),
        ('pharmacies', '0004_pharmacy_is_on_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_phone', models.CharField(db_index=True, help_text="E.164, snapshotted at creation so a later address/profile edit can't break inbound WhatsApp matching.", max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('order_fulfillment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='orders.orderfulfillment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Pharmacy/system to shopper'), ('INBOUND', 'Shopper to pharmacy')], max_length=10)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], default='QUEUED', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender_user', models.ForeignKey(blank=True, help_text='Null for inbound (shopper via WhatsApp) messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
