# Generated by Django 5.1.15 on 2026-08-23 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0003_prescription_renewed_from_and_more'),
        ('messaging', '0001_initial'),
        ('orders', '0004_alter_orderfulfillment_status'),
        ('pharmacies', '0004_pharmacy_is_on_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='doctor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='eprescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer_phone',
            field=models.CharField(db_index=True, help_text="E.164 phone of the non-pharmacy party (shopper or doctor), snapshotted at creation so a later profile edit can't break inbound WhatsApp matching.", max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='order_fulfillment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='orders.orderfulfillment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND', "Sent from the app (pharmacy or doctor) to the other party's WhatsApp"), ('INBOUND', "Reply from the other party's WhatsApp")], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_fulfillment__isnull', False), ('prescription__isnull', True)), models.Q(('order_fulfillment__isnull', True), ('prescription__isnull', False)), _connector='OR'), name='conversation_anchor_xor_fulfillment_prescription'),
        ),
    ]
