# Generated by Django 5.1.15 on 2026-08-29 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_doctor_user_conversation_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ORDER_UPDATE', 'Order update'), ('REFILL_REMINDER', 'Refill reminder'), ('PHARMACY_ALERT', 'Pharmacy alert'), ('PRESCRIPTION_EXPIRY', 'Prescription expiry'), ('RENEWAL_DECISION', 'Renewal decision'), ('PAYMENT_FAILURE', 'Payment failure')], db_index=True, max_length=32)),
                ('deduplication_key', models.CharField(max_length=180, unique=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=120)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('body_parameters', models.JSONField(default=list)),
                ('button_url_suffix', models.CharField(blank=True, max_length=255)),
                ('fallback_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], default='QUEUED', max_length=12),
        ),
    ]
