# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_medicine_category_medicine_price_regime_and_more'),
        ('pharmacies', '0002_pharmacy_accepts_online_orders_pharmacy_closes_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='POS connector', max_length=120)),
                ('key_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('secret_encrypted', models.TextField()),
                ('secret_fingerprint', models.CharField(blank=True, max_length=16)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_integration_keys', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_keys', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('secret', models.CharField(help_text='Used to sign the payload so the receiver can verify it came from us.', max_length=80)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=80)),
                ('integration_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='integrations.integrationkey')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='integration_created_98984d_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration_key', 'nonce'), name='unique_nonce_per_key')],
            },
        ),
        migrations.CreateModel(
            name='SkuMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_code', models.CharField(db_index=True, max_length=120)),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('match_method', models.CharField(choices=[('MANUAL', 'Confirmed by pharmacy'), ('AUTO_EXACT', 'Exact catalog match'), ('AUTO_FUZZY', 'Fuzzy catalog match'), ('UNMATCHED', 'Not matched yet')], default='UNMATCHED', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_ignored', models.BooleanField(default=False, help_text="Set for the pharmacy's non-pharma lines that should never sync.")),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sku_mappings', to='medicines.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_mappings', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['external_name', 'external_code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('external_code'), models.F('pharmacy'), name='unique_external_code_per_pharmacy')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('STOCK', 'Stock levels'), ('SALES', 'Sales')], max_length=20)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('PARTIAL', 'Partially applied'), ('REJECTED', 'Rejected'), ('REPLAYED', 'Duplicate, previous result returned')], default='APPLIED', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=80)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_applied', models.PositiveIntegerField(default=0)),
                ('rows_unmapped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('response_payload', models.JSONField(default=dict)),
                ('error_summary', models.TextField(blank=True)),
                ('integration_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='integrations.integrationkey')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'idempotency_key'), name='unique_idempotency_key_per_pharmacy')],
            },
        ),
    ]
