# Generated by Django 5.1.15 on 2026-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed (retries exhausted)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
