# Generated by Django 5.1.15 on 2026-08-22 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0004_alter_orderfulfillment_status'),
        ('pharmacies', '0003_pharmacyapplication'),
        ('sales', '0002_sale_channel_sale_client_alter_sale_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('copay_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insuranceprovider')),
            ],
            options={
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(max_length=80)),
                ('holder_name', models.CharField(max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='customers.client')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('covered_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patient_copay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='SUBMITTED', max_length=20)),
                ('approval_code', models.CharField(blank=True, max_length=80)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order_fulfillment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim', to='orders.orderfulfillment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='pharmacies.pharmacy')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim', to='sales.sale')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.patientinsurancepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='insuranceplan',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='unique_plan_name_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='patientinsurancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer_user__isnull', False), ('client__isnull', True)), models.Q(('customer_user__isnull', True), ('client__isnull', False)), _connector='OR'), name='policy_owner_xor_customer_user_client'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['pharmacy', 'status'], name='insurance_i_pharmac_f12d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='insuranceclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_fulfillment__isnull', False), ('sale__isnull', True)), models.Q(('order_fulfillment__isnull', True), ('sale__isnull', False)), _connector='OR'), name='claim_source_xor_fulfillment_sale'),
        ),
    ]
