# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_medicine_category_medicine_price_regime_and_more'),
        ('pharmacies', '0002_pharmacy_accepts_online_orders_pharmacy_closes_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_area', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('ORDER_OF_PHYSICIANS', 'Order of Physicians roster'), ('MANUAL', 'Manually added')], default='ORDER_OF_PHYSICIANS', max_length=32)),
                ('roster_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Cleared when the Order of Physicians suspends the licence.')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('pin_hash', models.CharField(max_length=64)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_phone', models.CharField(blank=True, max_length=40)),
                ('patient_date_of_birth', models.DateField(blank=True, null=True)),
                ('diagnosis_note', models.TextField(blank=True, help_text='Free note for the dispensing pharmacist. Not a diagnosis service.')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIALLY_DISPENSED', 'Partially dispensed'), ('FULLY_DISPENSED', 'Fully dispensed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=24)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_auth_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, help_text='Set after repeated failed PIN attempts.', null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='eprescriptions.doctor')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_attempted', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DISPENSE', 'Dispensed'), ('AUTH_FAILED', 'Authentication failed'), ('LOCKED', 'Locked out')], max_length=20)),
                ('method', models.CharField(blank=True, help_text='QR or MANUAL', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='eprescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('pharmacist_name', models.CharField(max_length=255)),
                ('pharmacist_license', models.CharField(blank=True, max_length=80)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('dispensed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_dispenses', to='pharmacies.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='eprescriptions.prescription')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_text', models.CharField(help_text='What the doctor wrote, kept verbatim.', max_length=255)),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('dosage_instructions', models.CharField(blank=True, max_length=255)),
                ('allow_generic_substitution', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eprescriptions.prescription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDispenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('substituted_with', models.CharField(blank=True, max_length=255)),
                ('dispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eprescriptions.prescriptiondispense')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_items', to='eprescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'issued_at'], name='eprescripti_doctor__9ce840_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionaccesslog',
            index=models.Index(fields=['prescription', 'created_at'], name='eprescripti_prescri_6b7d6a_idx'),
        ),
    ]
