# Generated by Django 5.1.15 on 2026-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pin_hash',
            field=models.CharField(max_length=128),
        ),
    ]
