# Generated by Django 5.1.15 on 2026-08-23 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0002_alter_prescription_pin_hash'),
        ('pharmacies', '0004_pharmacy_is_on_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='renewed_from',
            field=models.ForeignKey(blank=True, help_text='Set on the fresh prescription created when a renewal request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='eprescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='target_pharmacy',
            field=models.ForeignKey(blank=True, help_text="Set when the doctor sends directly to the patient's chosen pharmacy. Left blank for deferred transmission (patient carries the QR/PIN to any pharmacy).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_prescriptions', to='pharmacies.pharmacy'),
        ),
        migrations.CreateModel(
            name='PrescriptionRenewalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=12)),
                ('response_note', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('new_prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_request_source', to='eprescriptions.prescription')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='eprescriptions.prescription')),
                ('requested_by_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='pharmacies.pharmacy')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescription', 'status'], name='eprescripti_prescri_aa0679_idx')],
            },
        ),
    ]
