# Generated by Django 5.1.15 on 2026-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprescriptions', '0003_prescription_renewed_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fax_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when the fax back-up delivered this prescription because the digital send failed or had no email to use.', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_fax',
            field=models.CharField(blank=True, help_text='Used only as a delivery back-up when the digital (email) send fails or no email is on file.', max_length=40),
        ),
    ]
