# Generated by Django 5.1.15 on 2026-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimportrow',
            name='price_note',
            field=models.TextField(blank=True, help_text='Set when the imported price was snapped to the MoPH regulated price.'),
        ),
    ]
