# Generated by Django 5.1.15 on 2026-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_inventoryimportrow_price_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimport',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the uploaded file, for duplicate-upload detection.', max_length=64),
        ),
    ]
