# Generated by Django 5.1.15 on 2026-07-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        ('pharmacies', '0002_pharmacy_accepts_online_orders_pharmacy_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='orders.order'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryroute'),
        ),
        migrations.AddField(
            model_name='routeevent',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='delivery.routestop'),
        ),
        migrations.AddField(
            model_name='routestoptask',
            name='order_fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_tasks', to='orders.orderfulfillment'),
        ),
        migrations.AddField(
            model_name='routestoptask',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.routestop'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_stop_sequence_per_route'),
        ),
    ]
