# Generated by Django 5.1.15 on 2026-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryroute',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('OFFERED', 'Offered to driver'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ISSUES', 'Completed with issues'), ('CANCELLED', 'Cancelled')], db_index=True, default='PROPOSED', max_length=22),
        ),
    ]
