# Generated by Django 5.1.15 on 2026-07-04 10:34

import apps.prescriptions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=60)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=apps.prescriptions.models.prescription_upload_path, validators=[apps.prescriptions.models.validate_prescription_file])),
                ('file_original_name', models.CharField(blank=True, max_length=255)),
                ('file_mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_records', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_records', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
