# Generated by Django 5.1.15 on 2026-08-13 10:25

import apps.prescriptions.models
import apps.prescriptions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='file',
            field=models.FileField(blank=True, storage=apps.prescriptions.storage.EncryptedPrescriptionStorage(), upload_to=apps.prescriptions.models.prescription_upload_path, validators=[apps.prescriptions.models.validate_prescription_file]),
        ),
    ]
