# Generated by Django 5.1.15 on 2026-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_prescriptionrecord_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='valid_until',
            field=models.DateField(blank=True, help_text='After this date the scan can no longer back a new sale. Defaults to prescription_date + PRESCRIPTION_VALIDITY_DAYS if left blank.', null=True),
        ),
    ]
