# Generated by Django 5.1.15 on 2026-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_prescriptionrecord_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Cached raw OCR transcription of `file`, populated on first request to extract candidate drug lines.'),
        ),
    ]
