# Generated by Django 5.1.15 on 2026-08-29 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacy_pos_system'),
        ('prescriptions', '0005_ocr_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='quality_findings',
            field=models.JSONField(blank=True, default=list, help_text='Server-side legibility check results at upload time ({code, message, severity}).'),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACCEPTED', help_text='Pharmacy-created records are ACCEPTED by definition. A patient upload starts PENDING_REVIEW until a pharmacy accepts or rejects it.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_records', to='pharmacies.pharmacy'),
        ),
    ]
