# Generated by Django 5.1.15 on 2026-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_patient_prescription_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='ocr_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Structured read of `ocr_text`: {patient_name, patient_phone, doctor_name, prescription_date, medications: [{name, strength, quantity, directions, duration, refills}], notes}. Shown to the patient read-only on a paper upload and editable by a pharmacist on review. Empty when extraction is off or failed.'),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='ocr_provider',
            field=models.CharField(blank=True, help_text="Which extractor produced `ocr_fields` ('regex', 'openai_compatible', ...).", max_length=40),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='ocr_review_note',
            field=models.CharField(blank=True, help_text='What the patient said was wrong with the OCR read.', max_length=500),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='ocr_review_requested',
            field=models.BooleanField(default=False, help_text='The patient flagged the OCR read as wrong; a pharmacist should re-check it before accepting.'),
        ),
    ]
