# Generated by Django 5.1.15 on 2026-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescriptionrecord_ocr_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='ocr_fields',
            field=models.JSONField(blank=True, default=dict, help_text="Structured read of `ocr_text`: {patient_name, patient_phone, doctor_name, prescription_date, medications: [{name, strength, quantity, directions, duration, refills, medicine_id, catalog_name, match_confidence}], notes}. Each medication's name is reconciled against the medicine catalog server-side (medicine_id/catalog_name/match_confidence). Shown to the patient read-only on a paper upload and editable by a pharmacist on review. Empty when extraction is off or failed."),
        ),
    ]
